---------------------------------------------------
-- This code is for logic purpose only and is NOT to be used in the final code : it is an idea of how to generate a working code
-- It has been generated by ChatGPT.  
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity Whackamole is
    port(
        clk       : in  std_logic;

        -- button matrix columns (inputs)
        key_cols  : in  std_logic_vector(5 downto 0);

        -- LED matrix outputs
        led_rows  : out std_logic_vector(5 downto 0);
        led_cols  : out std_logic_vector(5 downto 0)
    );
end entity;

architecture rtl of Whackamole is

-- row scanning
signal scan_row : integer range 0 to 5 := 0;

-- mole position
signal mole_row : integer range 0 to 5 := 0;
signal mole_col : integer range 0 to 5 := 0;

-- random generator
signal lfsr : std_logic_vector(5 downto 0) := "101011";

-- hit signal
signal hit : std_logic := '0';

-- clock divider for scan
signal divider : unsigned(15 downto 0) := (others => '0');
signal scan_tick : std_logic;

begin

---------------------------------------------------
-- clock divider (slows scanning)
---------------------------------------------------

process(clk)
begin
    if rising_edge(clk) then
        divider <= divider + 1;
    end if;
end process;

scan_tick <= divider(12);

---------------------------------------------------
-- row scanner
---------------------------------------------------

process(clk)
begin
    if rising_edge(clk) then
        if scan_tick = '1' then
            if scan_row = 5 then
                scan_row <= 0;
            else
                scan_row <= scan_row + 1;
            end if;
        end if;
    end if;
end process;

---------------------------------------------------
-- LED row driver
---------------------------------------------------

process(scan_row)
begin
    led_rows <= (others => '0');

    case scan_row is
        when 0 => led_rows(0) <= '1';
        when 1 => led_rows(1) <= '1';
        when 2 => led_rows(2) <= '1';
        when 3 => led_rows(3) <= '1';
        when 4 => led_rows(4) <= '1';
        when 5 => led_rows(5) <= '1';
        when others => null;
    end case;

end process;

---------------------------------------------------
-- LED column logic (display mole)
---------------------------------------------------

process(scan_row, mole_row, mole_col)
begin

    led_cols <= (others => '0');

    if scan_row = mole_row then
        led_cols(mole_col) <= '1';
    end if;

end process;

---------------------------------------------------
-- button hit detection
---------------------------------------------------

process(clk)
begin
    if rising_edge(clk) then

        hit <= '0';

        if scan_row = mole_row then
            if key_cols(mole_col) = '1' then
                hit <= '1';
            end if;
        end if;

    end if;
end process;

---------------------------------------------------
-- LFSR random generator
---------------------------------------------------

process(clk)
begin
    if rising_edge(clk) then
        lfsr <= lfsr(4 downto 0) & (lfsr(5) xor lfsr(4));
    end if;
end process;

---------------------------------------------------
-- new mole position
---------------------------------------------------

process(clk)
begin
    if rising_edge(clk) then

        if hit = '1' then
            mole_row <= to_integer(unsigned(lfsr(2 downto 0))) mod 6;
            mole_col <= to_integer(unsigned(lfsr(5 downto 3))) mod 6;
        end if;

    end if;
end process;

end architecture;